### PR TITLE
Allow access to more than one module inside library 

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by kiwidoggie — APPROVED** [review]
Pending final testing before merging

**Comment by CrazyVoid** [comment]
I'm not great with the go lang, but have you verified you are able to determine which function belongs to which module inside the library?

for example, if you loaded the library libSceSystemService.prx and wanted to use a function from each module (libSceLncUtil,  libSceSystemStateMgr, libSceSystemServicePowerControl). 

Is your code able to determine which function belongs to which module?

**Comment by ghost** [comment]
@CrazyVoid It should.

**Comment by ghost** [comment]
The only issues with compiling I'm having is with the linker not find FreeType symbols for certain sample projects. Otherwise, all the other projects compile with no errors. I'm using the  `build-all.sh` script to test.

**Pull request merged**
